### ISSUE TITLE
cocoaspod 0.39 with awaitkit

### ISSUE THREAD

**Issue by arden** [yannickl/AwaitKit#1]
i'm use cocoaspod 0.39, when i'm run pod update, there some errors below:
[!] Unable to find a specification for `AwaitKit (~> 1.0.0)`

the awaitkit must to use cocoapod 1.0.0?

**Comment by yannickl** [comment]
Hi arden,

This is normal, for the moment the _AwaitKit_ is still under dev and I didn't published it to cocoapods yet.

I push a modification to the _PromiseKit_ and I need to wait for merge and new release before...

For the moment, if you want test or use it in your project you will you to copy the files manually and add this line to your Podfile: `pod 'PromiseKit', :git => 'https://github.com/yannickl/PromiseKit'`

**Comment by arden** [comment]
@yannickl  i see, thanks.

**Comment by yannickl** [comment]
FYI I just published the library. So you can now use it via CocoaPods.
