### ISSUE TITLE
Patch release for package.swift change

### ISSUE THREAD

**Issue by jnewc** [yannickl/AwaitKit#11]
Any chance of a patch release with the package.swift update? It's not possible to add this as a dependency currently without it. Commit hash is ad8e892d934046799f5767293f19cfd616302b8c.

**Comment by jnewc** [comment]
Also requires tests to be moved into a module.

I'll update with other required changes as I make them on my fork, not sure if it's feasible to patch release only these changes so apologies if it isn't.

**Comment by yannickl** [comment]
Hi @jnewc,

I'll update the project version in the next few days. So feel free to update the package.swift (and the tests) and then make a pull request. 👍

**Comment by jnewc** [comment]
Thanks @yannickl, PR incoming 😁

**Comment by jnewc** [comment]
Opened #12

**Comment by jnewc** [comment]
Closing. @yannickl will you be cutting a minor release or are you planning more updates? (I can continue working from the fork for now if needed)

**Comment by yannickl** [comment]
I just released the `3.0.0` version! So i close this issue. 🔒
