### ISSUE TITLE
Fails to build using carthage

### ISSUE THREAD

**Issue by ghost** [yannickl/AwaitKit#13]
I've been trying to build this library, using Carthage, but it's failed with error:
`error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.`
Is something can be done about it?

**Comment by yannickl** [comment]
Hi @v-vodyanov,

I've deintegrate the Cocoapods, is it working now with the master branch?

**Comment by ghost** [comment]
Not really, error changed, but it still can't compile, here is the new one:

```
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
.../Carthage/Checkouts/AwaitKit/Sources/DispatchQueue+Async.swift:28:8: error: no such module 'PromiseKit'
```

**Comment by willks** [comment]
@v-vodyanov 
I could not get it working either. I tried to work around it using this project - it's temporary and based on current master.

https://github.com/willks/AwaitKit/

I'll take down this repo when I manage to get Carthage builds working for AwaitKit

**Comment by ArifADS** [comment]
Looks like AwaitKit still doesn't support Carthage :(

**Comment by ArifADS** [comment]
Any update on this?

**Comment by arturgrigor** [comment]
@yannickl, @ArifADS I've added support for Carthage with this PR: https://github.com/yannickl/AwaitKit/pull/18.

@ArifADS If you want you can use `github "arturgrigor/AwaitKit"` in your Cartfile until this PR is merged.

**Comment by yannickl** [comment]
I've just push the tag `3.0.2` with the @arturgrigor carthage fix. It should works now!

Thank you again @arturgrigor!
