### ISSUE TITLE
Swift4 support

### ISSUE THREAD

**Issue by yannickl** [yannickl/AwaitKit#16]

**Comment by hy9be** [comment]
What issues should we expect when choosing Swift4 over Swift3.2 in Xcode?

**Comment by cloutiertyler** [comment]
I've created #22. It updates the Package.swift file and fixes issues related to "tuplegate". 

https://github.com/mxcl/PromiseKit/issues/697

**Comment by cloutiertyler** [comment]
Also, in case you guys haven't already seen it. Check out https://gist.github.com/lattner/429b9070918248274f25b714dcfc7619 when you get a chance. Exciting stuff!

**Comment by cloutiertyler** [comment]
AwaitKit is a magical thing you've done here, by the way! Thanks so much!

**Comment by jacknewcombe-je** [comment]
@yannickl hey, any plans to merge this?

**Comment by jnewc** [comment]
@yannickl hey, any plans to merge this?
