### ISSUE TITLE
Crashing on iOS11 device

### ISSUE THREAD

**Issue by eriadam** [yannickl/AwaitKit#17]
Hello @yannickl,

Love the framework, great work!
Maybe it is connected to #16, building the app with the iOS11 SDK, it crashes on the device (not on simulator, though).

  - 0 : "0   ???                                 0x0000000109880474 0x0 + 4454876276"
  - 1 : "1   App Development                 0x0000000103e11e1c main + 0"
  - 2 : "2   AwaitKit                            0x0000000104721ca0 _T08AwaitKit9ExtensionCAASo13DispatchQueueCRbzlE5awaitqd__07PromiseB00G0Cyqd__GKlF + 2020"
  - 3 : "3   AwaitKit                            0x0000000104720810 _T08AwaitKit5awaitx07PromiseB00D0CyxGKlF + 172"
  - 4 : "4   App Development                 0x0000000103e110e0 _T019App_Development11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySo0F16LaunchOptionsKeyVypGSg022didFinishLaunchingWithI0tFyycfU_ + 352"
  - 5 : "5   AwaitKit                            0x00000001047211f0 _T0s5Error_pIxzo_ytsAA_pIxrzo_TR + 32"
  - 6 : "6   AwaitKit                            0x00000001047212e4 _T0s5Error_pIxzo_ytsAA_pIxrzo_TRTA + 88"
  - 7 : "7   PromiseKit                          0x00000001069820ac _T0So13DispatchQueueC10PromiseKitE7promiseAC0C0CyxGSo0A5GroupCSg5group_0A00A3QoSV3qosAL0A13WorkItemFlagsV5flagsxyKc7executetlFyyAC10ResolutionOyxGccfU_yycfU_ + 216"
  - 8 : "8   PromiseKit                          0x00000001069737b0 _T0Ix_IyB_TR + 48"
  - 9 : "9   libdispatch.dylib                   0x000000010764f334 _dispatch_block_async_invoke_and_release + 100"
  - 10 : "10  libdispatch.dylib                   0x0000000107641d4c _dispatch_client_callout + 16"
  - 11 : "11  libdispatch.dylib                   0x000000010764f9a0 _dispatch_continuation_pop + 624"
  - 12 : "12  libdispatch.dylib                   0x000000010764de48 _dispatch_async_redirect_invoke + 684"
  - 13 : "13  libdispatch.dylib                   0x0000000107654080 _dispatch_root_queue_drain + 616"
  - 14 : "14  libdispatch.dylib                   0x0000000107653db8 _dispatch_worker_thread4 + 68"
  - 15 : "15  libsystem_pthread.dylib             0x00000001864bf338 _pthread_wqthread + 1260"
  - 16 : "16  libsystem_pthread.dylib             0x00000001864bee40 start_wqthread + 4"

The exception brake point stops at DispatchQueue+AwaitKit,swift line 79.

**Comment by yannickl** [comment]
Thank you for the report @eriadam,

I don't have any device in iOS11 for the moment. Once I'll find one I will try it.

**Comment by igordeoliveirasa** [comment]
Oh no!

**Comment by hy9be** [comment]
Observed the same issue:

I used to use ``await`` to queue up my task executions
``` swift
for a in self.aaa {
    try await(self.do[a].execute())
}
```
But I upgraded to ios 11 today and run into a EXC_BREAKPOINT here. The call stack is
![image](https://user-images.githubusercontent.com/3392907/28939909-e27e62a2-7860-11e7-9274-3335f017e772.png)

And the error is
![image](https://user-images.githubusercontent.com/3392907/28939935-f5f9646c-7860-11e7-9389-af4ec0c9cf3a.png)

**Comment by hy9be** [comment]
@yannickl could you please take a look, or give us some hint to fix it. ios 11 release is right around the corner. Our app is going to be useless if we cannot fix this problem by then. Thanks!!!

**Comment by yannickl** [comment]
I've found an iPad with iOS 11, I'll test it tomorrow. I don't know what is the issue, may be the `UInt64.max` which is not allowed now...

**Comment by hy9be** [comment]
lol. I hope not...thanks! Let me know if I can help on anything.

**Comment by yannickl** [comment]
As I thought, the issue came from `DispatchTime(uptimeNanoseconds: UInt64.mx)`. I replaced it with the `DispatchTime.distantFuture` and it works perfectly!

**Comment by hy9be** [comment]
@yannickl I updated the library and now get stuck at the line you made the change from ``UInt64.mx)`` to ``.distantFuture``. Have you seen similar problems when you made the fix?

**Comment by yannickl** [comment]
@hy9be what kind of problems have you?

**Comment by hy9be** [comment]
@yannickl Stuck at ``await`` statement. No CPU usage, no network or IO activities. If I pause the execution of the app in xcode, the code stops at the line: https://github.com/yannickl/AwaitKit/blob/cd5a8cae34606d5d160ee5e35a8ad84c851aee76/Sources/DispatchQueue%2BAwait.swift#L79

My code is very simple:
``` swift
for mission in self.missions {
    try await(mission.execute())
}
```

``mission.execute()`` returns a promise.

**Comment by J7mbo** [comment]
@hy9be I have the same issue - is this fixed?

**Comment by hy9be** [comment]
@J7mbo J I have not tested recently.

**Comment by Mijail** [comment]
maybe you should place it inside an async { } block. But that leaves me with the question: how do you get to the main thread again if you have to be inside asyncs all the time?
