### ISSUE TITLE
PromiseKit 4.5.1 incompatible

### ISSUE THREAD

**Issue by jnewc** [yannickl/AwaitKit#23]
Currently AwaitKit points fuzzily at 4.x, but 4.5.1 raises it's deployment target version to 10.11.

If there's no appetite to increment the deployment target to 10.11, the alternative is to pin the PromiseKit version in the podspec

Happy to PR this if needed.

**Comment by yannickl** [comment]
Hi @jnewc, sorry for the inconvenience, I just released a new version (4.0.0) which support the PromiseKit 4.5.1 version.

**Comment by jnewc** [comment]
Brilliant, thanks for the quick response!
