### ISSUE TITLE
Migration to Swift 3

### ISSUE THREAD

**Issue by yannickl** [yannickl/AwaitKit#4]
Create a new `swift3` branch and update the APIs to be conform to the [Swift API Guideline](https://swift.org/documentation/api-design-guidelines/).

**Comment by mxcl** [comment]
There's a branch for PromiseKit now: https://github.com/mxcl/PromiseKit/tree/swift-3.0

**Comment by yannickl** [comment]
I'm waiting for https://github.com/CocoaPods/CocoaPods/issues/5864 before to be able to publish the new version.

**Comment by jonybur** [comment]
Will this library be using PromiseKit 4.0?

**Comment by yannickl** [comment]
@jonybur Yes of course! The new version will be released today. ;)

**Comment by yannickl** [comment]
V.2.0.0 is now out!
