### ISSUE TITLE
XCode 10.2 compatibility

### ISSUE THREAD

**Issue by martinbonnin** [yannickl/AwaitKit#42]
It's not possible to build the project with XCode 10.2:

    The target “PromiseKit” contains source code developed with Swift 3.x. 
    This version of Xcode does not support building or migrating Swift 3.x targets.

**Comment by Mijail** [comment]
See my pull request

**Comment by martinbonnin** [comment]
@Mijail works for me, thanks

**Comment by yannickl** [comment]
Related to #41

**Comment by martinbonnin** [comment]
Thanks! Any chance you can make a release?

**Comment by yannickl** [comment]
I will do that this weekend I think.

**Comment by martinbonnin** [comment]
FYI, it looks like the PromiseKit commit has become orphan these last days. I made a PR there to make it point to a valid commit: https://github.com/yannickl/AwaitKit/pull/44
