### ISSUE TITLE
DispatchQueue.async ambiguous in swift 3.0

### ISSUE THREAD

**Issue by crfeliz** [yannickl/AwaitKit#9]
The DispatchQueue extension in this library which adds the .async method conflicts with the one provided by swift 3.0 (dispatch_async was replaced with DispatchQueue.async). Explicitly specifying the parameter name (execute:) works around the issue but I think this extension method needs to be renamed so that it does not conflict with iOS standard libs.

**Comment by humblehacker** [comment]
Thanks for the feedback, but if you're using Swift 3, there's no reason to use this library. Dispatch3 was built only to provide the new Swift 3 syntax to users of Swift 2.  Best to just remove it from your project.

**Comment by crfeliz** [comment]
This is not regarding Dispatch3. This is regarding AwaitKit which uses
async to wrap a sequence of awaits.

**Comment by humblehacker** [comment]
Yep, realized my mistake seconds after posting and deleted my comment, but not quick enough.  Sorry for the noise.

**Comment by yannickl** [comment]
Yes you've right, may be should we prefix it with `ak` or something similar?

```swift
DispatchQueue.main.ak.async {
  // ...
}

// or?

DispatchQueue.main.ak_async {
  // ...
}
```
